// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'pairing.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `prepare_transfer_files`, `send_to_device`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PreparedTransferFile`, `PreparedTransferSet`, `TransferSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StagedTempFiles>>
abstract class StagedTempFiles implements RustOpaqueInterface {
  static Future<StagedTempFiles> default_() => RustLib.instance.api.crateApiPairingStagedTempFilesDefault();
}

class JoinedPairingDevice {
  final PairingDeviceInfo device;
  final BigInt joinedAtMs;

  const JoinedPairingDevice({
    required this.device,
    required this.joinedAtMs,
  });

  @override
  int get hashCode => device.hashCode ^ joinedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinedPairingDevice && runtimeType == other.runtimeType && device == other.device && joinedAtMs == other.joinedAtMs;
}

class PairingDeviceInfo {
  final String fingerprint;
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final String ip;
  final int port;
  final ProtocolType protocol;
  final bool hasWebInterface;

  const PairingDeviceInfo({
    required this.fingerprint,
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.ip,
    required this.port,
    required this.protocol,
    required this.hasWebInterface,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      ip.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      hasWebInterface.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingDeviceInfo &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          ip == other.ip &&
          port == other.port &&
          protocol == other.protocol &&
          hasWebInterface == other.hasWebInterface;
}

class PairingJoinRequest {
  final String sessionToken;
  final String fingerprint;
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final int port;
  final ProtocolType protocol;
  final bool hasWebInterface;

  const PairingJoinRequest({
    required this.sessionToken,
    required this.fingerprint,
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.port,
    required this.protocol,
    required this.hasWebInterface,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^
      fingerprint.hashCode ^
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      hasWebInterface.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingJoinRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          fingerprint == other.fingerprint &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          port == other.port &&
          protocol == other.protocol &&
          hasWebInterface == other.hasWebInterface;
}

class PairingJoinResponse {
  final bool success;
  final PairingDeviceInfo sender;

  const PairingJoinResponse({
    required this.success,
    required this.sender,
  });

  @override
  int get hashCode => success.hashCode ^ sender.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingJoinResponse && runtimeType == other.runtimeType && success == other.success && sender == other.sender;
}

class PairingSendOffer {
  final String alias;
  final int? avatarIndex;
  final String sessionId;
  final String joinToken;
  final BigInt expiresAtMs;

  const PairingSendOffer({
    required this.alias,
    this.avatarIndex,
    required this.sessionId,
    required this.joinToken,
    required this.expiresAtMs,
  });

  @override
  int get hashCode => alias.hashCode ^ avatarIndex.hashCode ^ sessionId.hashCode ^ joinToken.hashCode ^ expiresAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingSendOffer &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          avatarIndex == other.avatarIndex &&
          sessionId == other.sessionId &&
          joinToken == other.joinToken &&
          expiresAtMs == other.expiresAtMs;
}

class PairingSessionSnapshot {
  final PairingDeviceInfo sender;
  final List<JoinedPairingDevice> joinedDevices;
  final bool closed;

  const PairingSessionSnapshot({
    required this.sender,
    required this.joinedDevices,
    required this.closed,
  });

  @override
  int get hashCode => sender.hashCode ^ joinedDevices.hashCode ^ closed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingSessionSnapshot &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          joinedDevices == other.joinedDevices &&
          closed == other.closed;
}

@freezed
sealed class RsPairingEvent with _$RsPairingEvent {
  const RsPairingEvent._();

  const factory RsPairingEvent.deviceJoined({
    required JoinedPairingDevice device,
  }) = RsPairingEvent_DeviceJoined;
  const factory RsPairingEvent.finalized() = RsPairingEvent_Finalized;
}

@freezed
sealed class RsPairingTransferEvent with _$RsPairingTransferEvent {
  const RsPairingTransferEvent._();

  const factory RsPairingTransferEvent.deviceStarted({
    required String fingerprint,
    required String alias,
  }) = RsPairingTransferEvent_DeviceStarted;
  const factory RsPairingTransferEvent.deviceFinished({
    required String fingerprint,
    required String alias,
    required int filesSent,
  }) = RsPairingTransferEvent_DeviceFinished;
  const factory RsPairingTransferEvent.deviceFailed({
    required String fingerprint,
    required String alias,
    required String error,
  }) = RsPairingTransferEvent_DeviceFailed;
}

class RsPairingTransferFile {
  final FileDto file;
  final String? path;
  final Uint8List? bytes;
  final int? fileDescriptor;

  const RsPairingTransferFile({
    required this.file,
    this.path,
    this.bytes,
    this.fileDescriptor,
  });

  @override
  int get hashCode => file.hashCode ^ path.hashCode ^ bytes.hashCode ^ fileDescriptor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsPairingTransferFile &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          path == other.path &&
          bytes == other.bytes &&
          fileDescriptor == other.fileDescriptor;
}
